# Copyright 2026 DataMasque Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this library except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

from importlib.metadata import version

from datamasque.client.dmclient import DataMasqueClient, FileOrContent
from datamasque.client.exceptions import (
    AsyncRulesetGenerationInProgressError,
    DataMasqueApiError,
    DataMasqueException,
    DataMasqueIfmError,
    DataMasqueNotReadyError,
    DataMasqueTransportError,
    DataMasqueUserError,
    DiscoveryConfigNotFoundError,
    FailedToStartError,
    IfmAuthError,
    InvalidDiscoveryConfigError,
    InvalidLibraryError,
    InvalidRulesetError,
    RGConfigNotFoundError,
    RunNotCancellableError,
)
from datamasque.client.ifm import DataMasqueIfmClient
from datamasque.client.models.connection import (
    AzureConnectionConfig,
    ConnectionConfig,
    ConnectionId,
    DatabaseConnectionConfig,
    DatabaseType,
    DatabricksConnectionConfig,
    DocumentDbConnectionConfig,
    DynamoConnectionConfig,
    FileConnectionConfig,
    MongoConnectionConfig,
    MountedShareConnectionConfig,
    MssqlLinkedServerConnectionConfig,
    S3ConnectionConfig,
    SnowflakeConnectionConfig,
    SnowflakeStageLocation,
    SseConfig,
    SseSelection,
)
from datamasque.client.models.data_selection import (
    HashColumnsTableConfig,
    JsonPath,
    Locator,
    SelectedColumns,
    SelectedData,
    SelectedFileData,
    UserSelection,
)
from datamasque.client.models.discovery import (
    ConstraintColumns,
    DiscoveryMatch,
    FileDataDiscoveryFromConfigRequest,
    FileDataDiscoveryOptions,
    FileDataDiscoveryRequest,
    FileDiscoveryFile,
    FileDiscoveryLocatorResult,
    FileDiscoveryMatch,
    FileDiscoveryResult,
    FileFilter,
    FileFilterMatchAgainst,
    FileRulesetGenerationRequest,
    FileRulesetGenerationWithRGConfigRequest,
    ForeignKeyRef,
    InDataDiscoveryConfig,
    InDataDiscoveryRule,
    ReferencingForeignKey,
    RulesetGenerationRequest,
    RulesetGenerationWithRGConfigRequest,
    SchemaDiscoveryColumn,
    SchemaDiscoveryFromConfigRequest,
    SchemaDiscoveryPage,
    SchemaDiscoveryRequest,
    SchemaDiscoveryResult,
    TableConstraints,
    ValueCountStatus,
)
from datamasque.client.models.discovery_config import DiscoveryConfig, DiscoveryConfigId, DiscoveryConfigType
from datamasque.client.models.discovery_config_library import DiscoveryConfigLibrary, DiscoveryConfigLibraryId
from datamasque.client.models.dm_instance import DataMasqueInstanceConfig
from datamasque.client.models.files import (
    DataMasqueFile,
    FileId,
    OracleWalletFile,
    SeedFile,
    SnowflakeKeyFile,
    SslZipFile,
)
from datamasque.client.models.git import GitSnapshot
from datamasque.client.models.ifm import (
    DataMasqueIfmInstanceConfig,
    IfmLog,
    IfmMaskRequest,
    IfmMaskResult,
    IfmRulesetPlanRef,
    IfmTokenInfo,
    RulesetPlan,
    RulesetPlanCreateRequest,
    RulesetPlanOptions,
    RulesetPlanPartialUpdateRequest,
    RulesetPlanUpdateRequest,
)
from datamasque.client.models.license import LicenseInfo, SwitchableLicenseMetadata
from datamasque.client.models.rg_config import RGConfig, RGConfigId
from datamasque.client.models.ruleset import Ruleset, RulesetId, RulesetType
from datamasque.client.models.ruleset_library import RulesetLibrary, RulesetLibraryId
from datamasque.client.models.runs import (
    MaskingRunOptions,
    MaskingRunRequest,
    MaskType,
    RunConnectionRef,
    RunId,
    RunInfo,
    UnfinishedRun,
)
from datamasque.client.models.safe_data_preview import (
    BooleanPreview,
    BooleanStatistics,
    ColumnKind,
    ColumnPreview,
    CommonStatistics,
    FirstCharsStatistics,
    LengthEntry,
    LengthsStatistics,
    MaskedFormEntry,
    NumericBin,
    NumericHistograms,
    NumericPreview,
    NumericStatistics,
    NumericSummaries,
    NumericTemporalDisclosureLevel,
    PatternComposition,
    PatternEntry,
    PatternsStatistics,
    SafeDataPreview,
    SafeDataPreviewOptions,
    StringDisclosureLevel,
    StringPreview,
    StringStatistics,
    TemporalBin,
    TemporalHistograms,
    TemporalPreview,
    TemporalStatistics,
    TemporalSummaries,
    UnsupportedPreview,
    UnsupportedStatistics,
)
from datamasque.client.models.status import (
    AsyncRulesetGenerationTaskStatus,
    MaskingRunStatus,
    ValidationErrorDetails,
    ValidationErrorType,
    ValidationStatus,
)
from datamasque.client.models.table_reference import (
    TableReference,
    TableReferenceFormat,
    TableReferenceId,
    TableReferenceOptions,
)
from datamasque.client.models.user import User, UserId, UserRole

__version__ = version("datamasque-python")

__all__ = [
    "AsyncRulesetGenerationInProgressError",
    "AsyncRulesetGenerationTaskStatus",
    "AzureConnectionConfig",
    "BooleanPreview",
    "BooleanStatistics",
    "ColumnKind",
    "ColumnPreview",
    "CommonStatistics",
    "ConnectionConfig",
    "ConnectionId",
    "ConstraintColumns",
    "DataMasqueApiError",
    "DataMasqueClient",
    "DataMasqueException",
    "DataMasqueFile",
    "DataMasqueIfmClient",
    "DataMasqueIfmError",
    "DataMasqueIfmInstanceConfig",
    "DataMasqueInstanceConfig",
    "DataMasqueNotReadyError",
    "DataMasqueTransportError",
    "DataMasqueUserError",
    "DatabaseConnectionConfig",
    "DatabaseType",
    "DatabricksConnectionConfig",
    "DiscoveryConfig",
    "DiscoveryConfigId",
    "DiscoveryConfigLibrary",
    "DiscoveryConfigLibraryId",
    "DiscoveryConfigNotFoundError",
    "DiscoveryConfigType",
    "DiscoveryMatch",
    "DocumentDbConnectionConfig",
    "DynamoConnectionConfig",
    "FailedToStartError",
    "FileConnectionConfig",
    "FileDataDiscoveryFromConfigRequest",
    "FileDataDiscoveryOptions",
    "FileDataDiscoveryRequest",
    "FileDiscoveryFile",
    "FileDiscoveryLocatorResult",
    "FileDiscoveryMatch",
    "FileDiscoveryResult",
    "FileFilter",
    "FileFilterMatchAgainst",
    "FileId",
    "FileOrContent",
    "FileRulesetGenerationRequest",
    "FileRulesetGenerationWithRGConfigRequest",
    "FirstCharsStatistics",
    "ForeignKeyRef",
    "GitSnapshot",
    "HashColumnsTableConfig",
    "IfmAuthError",
    "IfmLog",
    "IfmMaskRequest",
    "IfmMaskResult",
    "IfmRulesetPlanRef",
    "IfmTokenInfo",
    "InDataDiscoveryConfig",
    "InDataDiscoveryRule",
    "InvalidDiscoveryConfigError",
    "InvalidLibraryError",
    "InvalidRulesetError",
    "JsonPath",
    "LengthEntry",
    "LengthsStatistics",
    "LicenseInfo",
    "Locator",
    "MaskType",
    "MaskedFormEntry",
    "MaskingRunOptions",
    "MaskingRunRequest",
    "MaskingRunStatus",
    "MongoConnectionConfig",
    "MountedShareConnectionConfig",
    "MssqlLinkedServerConnectionConfig",
    "NumericBin",
    "NumericHistograms",
    "NumericPreview",
    "NumericStatistics",
    "NumericSummaries",
    "NumericTemporalDisclosureLevel",
    "OracleWalletFile",
    "PatternComposition",
    "PatternEntry",
    "PatternsStatistics",
    "RGConfig",
    "RGConfigId",
    "RGConfigNotFoundError",
    "ReferencingForeignKey",
    "Ruleset",
    "RulesetGenerationRequest",
    "RulesetGenerationWithRGConfigRequest",
    "RulesetId",
    "RulesetLibrary",
    "RulesetLibraryId",
    "RulesetPlan",
    "RulesetPlanCreateRequest",
    "RulesetPlanOptions",
    "RulesetPlanPartialUpdateRequest",
    "RulesetPlanUpdateRequest",
    "RulesetType",
    "RunConnectionRef",
    "RunId",
    "RunInfo",
    "RunNotCancellableError",
    "S3ConnectionConfig",
    "SafeDataPreview",
    "SafeDataPreviewOptions",
    "SchemaDiscoveryColumn",
    "SchemaDiscoveryFromConfigRequest",
    "SchemaDiscoveryPage",
    "SchemaDiscoveryRequest",
    "SchemaDiscoveryResult",
    "SeedFile",
    "SelectedColumns",
    "SelectedData",
    "SelectedFileData",
    "SnowflakeConnectionConfig",
    "SnowflakeKeyFile",
    "SnowflakeStageLocation",
    "SseConfig",
    "SseSelection",
    "SslZipFile",
    "StringDisclosureLevel",
    "StringPreview",
    "StringStatistics",
    "SwitchableLicenseMetadata",
    "TableConstraints",
    "TableReference",
    "TableReferenceFormat",
    "TableReferenceId",
    "TableReferenceOptions",
    "TemporalBin",
    "TemporalHistograms",
    "TemporalPreview",
    "TemporalStatistics",
    "TemporalSummaries",
    "UnfinishedRun",
    "UnsupportedPreview",
    "UnsupportedStatistics",
    "User",
    "UserId",
    "UserRole",
    "UserSelection",
    "ValidationErrorDetails",
    "ValidationErrorType",
    "ValidationStatus",
    "ValueCountStatus",
]
